from docx import Document

doc = Document()
doc.add_paragraph("TITLE: The Lost Kingdom")
doc.add_paragraph("Chapter 1 - The Beginning")
doc.add_paragraph("The sun rose over the ancient castle, casting long shadows across the courtyard.")
doc.add_paragraph("[thunder]")
doc.add_paragraph('Arthur: "We must leave before dawn, the enemy approaches!"')
doc.add_paragraph('Elena: "I am not afraid. Let them come."')
doc.add_paragraph("[footsteps]")
doc.add_paragraph("The knight drew his sword and stepped forward bravely.")
doc.add_paragraph("---")
doc.add_paragraph("The forest was dark and silent, only the wind spoke.")
doc.add_paragraph('Arthur: "Do you hear that? Something is coming."')
doc.add_paragraph("[wind]")
doc.add_paragraph("[suspense]")
doc.add_paragraph('Elena: "Stay close. We will survive this together."')
doc.save("test_script.docx")
print("Test DOCX created")
